version: 0.0
os: linux
files:
  - source: /codedeploytest.html
    destination: /usr/share/nginx/html/
hooks:
  AfterInstall:
    - location: scripts/restart_server
      timeout: 300
      runas: root
